# 组合挂起函数

（原文档 Last modified: 27 June 2022）

本节介绍组合挂起函数的各种方法。

# 默认顺序

假设我们有两个在别处定义的挂起函数，它们做一些有用的事情，比如某种远程服务调用或计算。我们只是假装它们很有用，但实际上每个人都只是为了这个例子的目的而延迟一秒钟：

```kotlin
suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

如果我们需要按 _顺序_ 调用它们，我们该怎么办——首先执行 `doSomethingUsefulOne` 然后执行 `doSomethingUsefulTwo`，然后计算它们的结果之和？实际上，如果我们使用第一个函数的结果来决定是否需要调用第二个函数或决定如何调用它，我们就会这样做。

我们使用正常的顺序调用，因为协程中的代码，就像在常规代码中一样，默认情况下是 _顺序的_ 。以下示例通过测量执行两个挂起函数所需的总时间来演示它：

```kotlin
import kotlinx.coroutines.*
import kotlin.system.*

fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        val one = doSomethingUsefulOne()
        val two = doSomethingUsefulTwo()
        println("The answer is ${one + two}")
    }
    println("Completed in $time ms")    
}

suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

它产生这样的东西：

```text
The answer is 42
Completed in 2017 ms
```

# 使用 async 进行并发操作

如果 `doSomethingUsefulOne` 和 `doSomethingUsefulTwo` 的调用之间没有依赖关系，并且我们希望通过同时执行这两项操作来更快地获得答案怎么办？这是异步提供帮助的地方。

从概念上讲，异步就像启动一样。它启动一个单独的协程，这是一个与所有其他协程同时工作的轻量级线程。不同之处在于 `launch` 返回一个 `Job` 并且不携带任何结果值，而 `async` 返回一个 [Deferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html) - 一个轻量级的非阻塞 future，代表稍后提供结果的承诺。您可以在延迟值上使用 `.await()` 以获得其最终结果，但 `Deferred` 也是一个 `Job` ，因此您可以在需要时取消它。

```kotlin
import kotlinx.coroutines.*
import kotlin.system.*

fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        val one = async { doSomethingUsefulOne() }
        val two = async { doSomethingUsefulTwo() }
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")    
}

suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

它产生这样的东西：

```text
The answer is 42
Completed in 1017 ms
```

这是两倍的速度，因为两个协程同时执行。请注意，协程的并发性始终是显式的。

# 懒惰地开始的 async

或者，可以通过将其启动参数设置为 `CoroutineStart.LAZY` 来使 `async` 变得惰性。在这种模式下，它仅在 `await` 需要其结果时或调用其 `Job` 的 [start](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-job/start.html) 函数时才启动协程。运行以下示例：

```kotlin
import kotlinx.coroutines.*
import kotlin.system.*

fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        val one = async(start = CoroutineStart.LAZY) { doSomethingUsefulOne() }
        val two = async(start = CoroutineStart.LAZY) { doSomethingUsefulTwo() }
        // some computation
        one.start() // start the first one
        two.start() // start the second one
        println("The answer is ${one.await() + two.await()}")
    }
    println("Completed in $time ms")    
}

suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

它产生这样的东西：

```text
The answer is 42
Completed in 1017 ms
```

因此，这里定义了两个协程，但没有像前面的示例那样执行，而是通过调用 `start` 将控制权交给程序员来确定何时开始执行。我们首先启动 `one` ，然后启动 `two`，然后等待各个协程完成。

请注意，如果我们只是在 println 中调用 `await` 而没有先在各个协程上调用 `start`，这将导致顺序行为，因为 `await` 启动协程执行并等待其完成，这不是 laziness 预期的用例。在计算值涉及挂起函数的情况下，`async(start = CoroutineStart.LAZY)` 的用例是标准 `lazy` 函数的替代品。

# 异步函数

我们可以使用 async 协程构建器定义异步调用 `doSomethingUsefulOne` 和 `doSomethingUsefulTwo` 的异步函数，使用 [GlobalScope](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-global-scope/index.html) 引用来选择退出结构化并发。我们用“...Async”后缀命名此类函数，以强调这样一个事实，即它们仅启动异步计算并且需要使用生成的 deferred 值来获取结果。

> GlobalScope 是一个微妙的 API，使用不当可能会以不寻常的方式适得其反，其中之一将在下面进行解释，因此您必须通过 `@OptIn(DelicateCoroutinesApi::class)` 明确选择加入使用 `GlobalScope`。

```kotlin
// The result type of somethingUsefulOneAsync is Deferred<Int>
@OptIn(DelicateCoroutinesApi::class)
fun somethingUsefulOneAsync() = GlobalScope.async {
    doSomethingUsefulOne()
}

// The result type of somethingUsefulTwoAsync is Deferred<Int>
@OptIn(DelicateCoroutinesApi::class)
fun somethingUsefulTwoAsync() = GlobalScope.async {
    doSomethingUsefulTwo()
}
```

请注意，这些 `xxxAsync` 函数 **不是** 挂起函数。它们可以在任何地方使用。然而，它们的使用总是意味着它们的操作与调用代码异步（这里指并发）执行。

以下示例显示了它们在协程之外的使用：

```kotlin
import kotlinx.coroutines.*
import kotlin.system.*

// note that we don't have `runBlocking` to the right of `main` in this example
fun main() {
    val time = measureTimeMillis {
        // we can initiate async actions outside of a coroutine
        val one = somethingUsefulOneAsync()
        val two = somethingUsefulTwoAsync()
        // but waiting for a result must involve either suspending or blocking.
        // here we use `runBlocking { ... }` to block the main thread while waiting for the result
        runBlocking {
            println("The answer is ${one.await() + two.await()}")
        }
    }
    println("Completed in $time ms")
}

@OptIn(DelicateCoroutinesApi::class)
fun somethingUsefulOneAsync() = GlobalScope.async {
    doSomethingUsefulOne()
}

@OptIn(DelicateCoroutinesApi::class)
fun somethingUsefulTwoAsync() = GlobalScope.async {
    doSomethingUsefulTwo()
}

suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

> 此处提供这种带有异步函数的编程风格只是为了说明，因为它是其他编程语言中的流行风格。出于以下解释的原因，**强烈建议不要** 将此样式与 Kotlin 协程一起使用。

考虑一下如果在 `val one = somethingUsefulOneAsync()` 行和 `one.await()` 表达式之间代码中存在一些逻辑错误，并且程序抛出异常，并且程序正在执行的操作中止，会发生什么情况。通常，全局错误处理程序可以捕获此异常，记录并向开发人员报告错误，但程序可以继续执行其他操作。但是，这里我们有 `somethingUsefulOneAsync` 仍在后台运行，即使启动它的操作已中止。如以下部分所示，结构化并发不会发生此问题。

# 异步的结构化并发

让我们以 [Concurrent using async](#使用 async 进行并发操作) 为例，提取一个同时执行 `doSomethingUsefulOne` 和 `doSomethingUsefulTwo` 并返回它们结果之和的函数。因为 async 协程构建器被定义为 [`CoroutineScope`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/index.html) 的扩展，所以我们需要将它包含在作用域中，这就是 [`coroutineScope`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html) 函数提供的功能：

```kotlin
suspend fun concurrentSum(): Int = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}
```

这样，如果 `concurrentSum` 函数的代码内部出现问题并抛出异常，则在其范围内启动的所有协程都将被取消。

```kotlin
import kotlinx.coroutines.*
import kotlin.system.*

fun main() = runBlocking<Unit> {
    val time = measureTimeMillis {
        println("The answer is ${concurrentSum()}")
    }
    println("Completed in $time ms")    
}

suspend fun concurrentSum(): Int = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}

suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

从上面的 main 函数的输出可以看出，我们仍然可以同时执行这两个操作：

```text
The answer is 42
Completed in 1017 ms
```

取消总是通过协程层次结构传播：

```kotlin
import kotlinx.coroutines.*

fun main() = runBlocking<Unit> {
    try {
        failedConcurrentSum()
    } catch(e: ArithmeticException) {
        println("Computation failed with ArithmeticException")
    }
}

suspend fun failedConcurrentSum(): Int = coroutineScope {
    val one = async<Int> { 
        try {
            delay(Long.MAX_VALUE) // Emulates very long computation
            42
        } finally {
            println("First child was cancelled")
        }
    }
    val two = async<Int> { 
        println("Second child throws an exception")
        throw ArithmeticException()
    }
    one.await() + two.await()
}
```

请注意第一个 `async` 和等待中的父级如何在其中一个子级（即 `two` ）失败时被取消：

```text
Second child throws an exception
First child was cancelled
Computation failed with ArithmeticException
```